export {
  type LifeDomain,
  type PrivacyLevel,
  type DataSource,
  type BodyPayload,
  type MoneyPayload,
  type PeoplePayload,
  type TimePayload,
  type MindPayload,
  type WorldPayload,
  type DomainPayload,
  type LifeEvent,
  lifeDomainSchema,
  privacyLevelSchema,
  dataSourceSchema,
  bodyPayloadSchema,
  moneyPayloadSchema,
  peoplePayloadSchema,
  timePayloadSchema,
  mindPayloadSchema,
  worldPayloadSchema,
  domainPayloadSchema,
  lifeEventSchema,
} from './life-schema.js';

export {
  type Ok,
  type Err,
  type Result,
  ok,
  err,
  isOk,
  isErr,
} from './result.js';
